version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: yuccanleaduser
      POSTGRES_PASSWORD: root
      POSTGRES_DB: yuccanleadfaq
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/yccanleadfaq
    ports:
      - "8000:8000"
    depends_on:
      - db
    